name: build-crx-package
on:
  release:
    types: [published]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - run: npm install -g crx
      - name: Check output
        env:
          RELEASE_VERSION: extn-${{ steps.vars.outputs.tag }}.crx
        run: crx pack -o ${{RELEASE_VERSION}}
      - name: check created
        run: ls -a
