name: build-crx-package
on:
  release:
    types: [published]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - run: npm install -g crx
      - name: Pack crx file
        env:
          RELEASE_VERSION: extn-${{ steps.vars.outputs.tag }}.crx
        run: crx pack -o $RELEASE_VERSION
      - name: check created
        run: ls
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_VERSION }}
          asset_name: ${{ env.RELEASE_VERSION }}
          asset_content_type: application/x-chrome-extension
